### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/scratchpad#1]
Could we change the icon to be this one instead:
https://material.io/tools/icons/?icon=list_alt&style=baseline

I don't want to use any dashicons to prevent confusion.

**Comment by nickhamze** [comment]
Can we get rid of the stroke around the icon?
<img width="248" alt="screen shot 2018-10-25 at 1 52 32 pm" src="https://user-images.githubusercontent.com/158918/47523297-54bc8800-d85d-11e8-84b9-a0ad51e15a99.png">


It currently looks like this:
<img width="176" alt="screen shot 2018-10-25 at 1 52 28 pm" src="https://user-images.githubusercontent.com/158918/47523313-5ab26900-d85d-11e8-9608-32b6c8816b84.png">

But without the stroke it looks like this which I think looks better:
<img width="54" alt="screen shot 2018-10-25 at 1 52 40 pm" src="https://user-images.githubusercontent.com/158918/47523337-69008500-d85d-11e8-86e4-2a93fbd912cc.png">

**Comment by jrtashjian** [comment]
Fixed in fd7722e.
